version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "4.3.x"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    target-branch: 4.3.x
    ignore:
      # only upgrade patch versions for maintenance branch
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    target-branch: main
    ignore:
      # only upgrade patch versions for maintenance branch
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: npm
    target-branch: docs-build
    directory: /
    ignore:
      # antora 3.2.0-alpha.12 is not compatible with the version of node we use so do not update it
      - dependency-name: "antora"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    target-branch: main
    directory: /docs
    ignore:
      # antora 3.2.0-alpha.12 is not compatible with the version of node we use so do not update it
      - dependency-name: "antora"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    target-branch: 4.3.x
    directory: /docs
    ignore:
      # antora 3.2.0-alpha.12 is not compatible with the version of node we use so do not update it
      - dependency-name: "antora"
    schedule:
      interval: weekly
