= Spring Cloud Config
:toc:

include::intro.adoc[]

== Quick Start

include::quickstart.adoc[]

== Spring Cloud Config Server

The Server provides an HTTP, resource-based API for external
configuration (name-value pairs, or equivalent YAML content).  The
server is easily embeddable in a Spring Boot application using the
`@EnableConfigServer` annotation.

=== Security

You are free to secure your Config Server in any way that makes sense
to you (from physical network security to OAuth2 bearer
tokens), and Spring Security and Spring Boot make it easy to do pretty
much anything. 

To use the default Spring Boot configured HTTP Basic security, just
include Spring Security on the classpath (e.g. through
`spring-boot-starter-security`). The default is a username of "user"
and a randomly generated password, which isn't going to be very useful
in practice, so we recommend you configure the password (via
`security.user.password`) and encrypt it (see below for instructions
on how to do that).

=== Encryption and Decryption

IMPORTANT: **Prerequisites:** to use the encryption and decryption features
you need the full-strength JCE installed in your JVM (it's not there by default).
You can download the "Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files"
from Oracle, and follow instructions for installation (essentially replace the 2 policy files
in the JRE lib/security directory with the ones that you downloaded).

The server exposes `/encrypt` and `/decrypt` endpoints (on the
assumption that these will be secured and only accessed by authorized
agents). If the remote property sources contain encryted content
(values starting with `{cipher}`) they will be decrypted before
sending to clients over HTTP. The main advantage of this set up is
that the property values don't have to be in plain text when they are
"at rest" (e.g. in a git repository). If a value cannot be decrypted
it is replaced with an empty string, largely to prevent cipher text
being used as a password in Spring Boot autconfigured HTTP basic.

If you are setting up a remote config repository for config client
applications it might contain an `application.yml` like this, for
instance:

.application.yml
----
spring:
  datasource:
    username: dbuser
    password: {cipher}FKSAJDFGYOS8F7GLHAKERGFHLSAJ
----

You can safely push this plain text to a shared git repository and the
secret password is protected.

If you are editing a remote config file you can use the Config Server
to encrypt values by POSTing to the `/encrypt` endpoint, e.g.

----
$ curl localhost:8888/encrypt -d mysecret
682bc583f4641835fa2db009355293665d2647dade3375c0ee201de2a49f7bda
----

The inverse operation is also available via `/decrypt` (provided the server is
configured with a symmetric key or a full key pair):

----
$ curl localhost:8888/decrypt -d 682bc583f4641835fa2db009355293665d2647dade3375c0ee201de2a49f7bda
mysecret
----

Take the encypted value and add the `{cipher}` prefix before you put
it in the YAML or properties file, and before you commit and push it
to a remote, potentially insecure store.

The `spring` command line client (with Spring Cloud CLI extensions
installed) can also be used to encrypt and decrypt, e.g.

----
$ spring encrypt mysecret --key foo
682bc583f4641835fa2db009355293665d2647dade3375c0ee201de2a49f7bda
$ spring decrypt --key foo 682bc583f4641835fa2db009355293665d2647dade3375c0ee201de2a49f7bda
mysecret
----

To use a key in a file (e.g. an RSA public key for encyption) prepend
the key value with "@" and provide the file path, e.g.

----
$ spring encrypt mysecret --key @${HOME}/.ssh/id_rsa.pub
AQAjPgt3eFZQXwt8tsHAVv/QHiY5sI2dRcR+...
----

=== Key Management

The Config Server can use a symmetric (shared) key or an asymmetric
one (RSA key pair). The asymmetric choice is superior in terms of
security, but it is often more convenient to use a symmetric key since
it is just a single property value to configure.

To configure a symmetric key you just need to set `encrypt.key` to a
secret String (or use an enviroment variable `ENCRYPT_KEY` to keep it
out of plain text configuration files). You can also POST a key value
to the `/key` endpoint (but that won't change any existing encrypted
values in remote repositories).

To configure an asymmetric key you can either set the key as a
PEM-encoded text value (in `encrypt.key`), or via a keystore (e.g. as
created by the `keytool` utility that comes with the JDK). The
keystore properties are `encrypt.keyStore.\*` with `*` equal to

* `location` (a `Resource` location), 
* `password` (to unlock the keystore) and 
* `alias` (to identify which key in the store is to be
used).

The encryption is done with the public key, and a private key is
needed for decryption. Thus in principle you can configure only the
public key in the server if you only want to do encryption (and are
prepared to decrypt the values yourself locally with the private
key). In practice you might not want to do that because it spreads the
key management process around all the clients, instead of
concentrating it in the server. On the other hand it's a useful option
if your config server really is relatively insecure and only a
handful of clients need the encrypted properties.

=== Creating a Key Store for Testing

To create a keystore for testing you can do something like this:

----
$ keytool -genkeypair -alias mytestkey -keyalg RSA \
  -dname "CN=Web Server,OU=Unit,O=Organization,L=City,S=State,C=US" \
  -keypass changeme -keystore server.jks -storepass letmein
----

Put the `server.jks` file in the classpath (for instance) and then in
your `application.yml` for the Config Server:

----
encrypt:
  keyStore:
    location: classpath:/server.jks
    alias: mytestkey
    password: letmein
----

=== Embedding the Config Server

The Config Server runs best as a standalone application, but if you
need to you can embed it in another application. Just use the
`@EnableConfigServer` annotation and (optionally) set
`spring.cloud.config.server.prefix` to a path prefix, e.g. "/config",
to serve the resources under a prefix. The prefix should start but not
end with a "/". It is applied to the `@RequestMappings` in the Config
Server (i.e. underneath the Spring Boot prefixes `server.servletPath`
and `server.contextPath`).

== Spring Cloud Config Client

A Spring Boot application can take immediate advantage of the Spring
Config Server (or other external property sources provided by the
application developer), and it will also pick up some additional
useful features related to `Environment` change events.

=== Config First Bootstrap

This is the default behaviour for any application wich has the Spring
Cloud Config Client on the classpath. When a config client starts up
it binds to the Config Server (via the bootstrap configuration
property `spring.cloud.config.uri`) and initializes Spring
`Environment` with remote property sources.

The net result of this is that all client apps that want to consume
the Config Server need a `bootstrap.yml` (or an environment variable)
with the server address in `spring.cloud.config.uri` (defaults to
"http://localhost:8888").

=== Eureka First Bootstrap

If you are using Spring Cloud Netflix and Eureka Service Discovery,
then you can have the Config Server register with Eureka if you want
to, but in the default "Config First" mode, clients won't be able to
take advantage of the registration.

If you prefer to use Eureka to locate the Config Server, you can do
that by setting `spring.cloud.config.discovery.enabled=true` (default
"false"). The net result of that is that client apps all need a
`bootstrap.yml` (or an environment variable) with the Eureka server
address, e.g. in `eureka.client.serviceUrl.defaultZone`.  The price
for using this option is an extra network round trip on start up to
locate the service registration. The benefit is that the Config Server
can change its co-ordinates, as long as Eureka is a fixed point.

=== Environment Changes

The application will listen for an `EnvironmentChangedEvent` and react
to the change in a couple of standard ways (additional
`ApplicationListeners` can be added as `@Beans` by the user in the
normal way). When an `EnvironmentChangedEvent` is observed it will
have a list of key values that have changed, and the application will
use those to:

* Re-bind any `@ConfigurationProperties` beans in the context
* Set the logger levels for any properties in `logging.level.*`

This covers a large class of refresh use cases, and you can verify the
changes by visiting the `/configprops` endpoint (normal Spring Boot
Actuator feature). For instance a `DataSource` can have its
`maxPoolSize` changed at runtime (the default `DataSource` created by
Spring Boot is an `@ConfigurationProperties` bean) and grow capacity
dynamically. It does not cover another large class of use cases, where
you need more control over the refresh, and where you need a
configuration change to be atomic over the whole
`ApplicationContext`. To address those concerns we have
`@RefreshScope`.

=== Refresh Scope

A Spring `@Bean` that is marked as `@RefreshScope` will get special
treatment when there is a configuration change. This addresses the
problem of stateful beans that only get their configuration injected
when they are initialized. For instance if a `DataSource` has open
connections when the database URL is changed via the `Environment`, we
probably want the holders of those connections to be able to complete
what they are doing. Then the next time someone borrows a connection
from the pool he gets one with the new URL.

Refresh scope beans are lazy proxies that initialize when they are
used (i.e. when a method is called), and the scope acts as a cache of
initialized values. To force a bean to re-initialize on the next
method call you just need to invalidate its cache entry.

The `RefreshScope` is a bean in the context and it has a public method
`refreshAll()` to refresh all beans in the scope by clearing the
target cache. There is also a `refresh(String)` method to refresh an
individual bean by name. This functionality is exposed in the
`/refresh` endpoint (over HTTP or JMX).

=== Encryption and Decryption

The Config Client has an `Environment` pre-processor for decrypting
property values locally. It follows the same rules as the Config
Server, and has the same external configuration via `encrypt.\*`. Thus
you can use encrypted values in the form `{cipher}*` and as long as
there is a valid key then they will be decrypted before the main
application context gets the `Environment`.

=== Endpoints

For a Spring Boot Actuator application there are some additional management endpoints:

* POST to `/env` to update the `Environment` and rebind `@ConfigurationProperties` and log levels
* `/refresh` for re-loading the boot strap context and refreshing the `@RefreshScope` beans
* `/restart` for closing the `ApplicationContext` and restarting it (disabled by default)
* `/pause` and `/resume` for calling the `Lifecycle` methods (`stop()` and `start()` on the `ApplicationContext`)


=== Locating Remote Configuration Resources

The Config Service serves property sources from `/{name}/{env}/{label}`, where the default bindings are

* "name" = `${spring.application.name}`
* "env" = `${spring.profiles.active}` (actually `Environment.getActiveProfiles()`)
* "label" = "master"

All of them can be overridden by setting `spring.cloud.config.\*`
(where `*` is "name", "env" or "label"). The "label" is useful for
rolling back to previous versions of configuration; with the default
Config Server implementation it can be a git label, branch name or
commit id.

=== The Bootstrap Application Context

The Config Client operates by creating a "bootstrap" application
context, which is a parent context for the main application. Out of
the box it is responsible for loading configuration properties from
the Config Server, and also decrypting properties in the local
external configuration files. The two contexts share an `Environment`
which is the source of external properties for any Spring
application. Bootstrap properties are added with high precedence, so
they cannot be overridden by local configuration.

The bootstrap context uses a different convention for locating
external configuration than the main application context, so instead
of `application.yml` (or `.properties`) you use `bootstrap.yml`,
keeping the external configuration for bootstrap and main context
nicely separate. Example:

.bootstrap.yml
----
spring:
  application:
    name: foo
  cloud:
    config:
      uri: ${SPRING_CONFIG_URI:http://localhost:8888}
----

It is a good idea to set the `spring.application.name` (in
`bootstrap.yml` or `application.yml`) if your application needs any
application-specific configuration from the server.

You can disable the bootstrap process completely by setting
`spring.cloud.bootstrap.enabled=false` (e.g. in System properties).

=== Application Context Hierarchies

If you build an application context from `SpringApplication` or
`SpringApplicationBuilder`, then the Bootstrap context is added as a
parent to that context. It is a feature of Spring that child contexts
inherit property sources and profiles from their parent, so the "main"
application context will contain additional property sources, compared
to building the same context without Spring Cloud Config. The
additional property sources are:

* "bootstrap": an optional `CompositePropertySource` appears with high
priority if any `PropertySourceLocators` are found in the Bootstrap
context, and they have non-empty properties. An example would be
properties from the Spring Cloud Config Server. See
link:#customizing-bootstrap-property-sources[below] for instructions
on how to customize the contents of this property source.

* "applicationConfig: [classpath:bootstrap.yml]" (and friends if
Spring profiles are active). If you have a `bootstrap.yml` (or
properties) then those properties are used to configure the Bootstrap
context, and then they get added to the child context when its parent
is set. They have lower precedence than the `application.yml` (or
properties) and any other property sources that are added to the child
as a normal part of the process of creating a Spring Boot
application. See link:#customizing-bootstrap-properties[below] for
instructions on how to customize the contents of these property
sources.

Because of the ordering rules of property sources the "bootstrap"
entries take precedence, but note that these do not contain any data
from `bootstrap.yml`, which has very low precedence, but can be used
to set defaults.

You can extend the context hierarchy by simply setting the parent
context of any `ApplicationContext` you create, e.g. using its own
interface, or with the `SpringApplicationBuilder` convenience methods
(`parent()`, `child()` and `sibling()`). Note that the
`SpringApplicationBuilder` allows you to share an `Environment`
amongst the whole hierarchy, but that is not the default. Thus,
normally you expect to see differences between different levels in the
hierarchy, and sibling contexts in particular do not need to have the
same profiles or property sources, even though they will share common
things with their parent. Every context in the hierarchy will have its
own "bootstrap" property source (possibly empty) to avoid promoting
values inadvertently from parents down to their descendants.

[[customizing-bootstrap-properties]]
=== Changing the Location of Bootstrap Properties

The `bootstrap.yml` (or `.properties) location can be specified using
`spring.cloud.bootstrap.name` (default "bootstrap") or
`spring.cloud.bootstrap.location` (default empty), e.g. in System
properties. Those properties behave like the `spring.config.*`
variants with the same name, in fact they are used to set up the
bootstrap `ApplicationContext` by setting those properties in its
`Environment`. If there is an active profile (from
`spring.profiles.active` or through the `Environment` API in the
context you are building) then properties in that profile will be
loaded as well, just like in a regular Spring Boot app, e.g. from
`bootstrap-development.properties` for a "development" profile.

=== Customizing the Bootstrap Configuration

The bootstrap context can be trained to do anything you like by adding
entries to `/META-INF/spring.factories` under the key
`org.springframework.cloud.bootstrap.BootstrapConfiguration`. This is
a comma-separated list of Spring `@Configuration` classes which will
be used to create the context. Any beans that you want to be available
to the main application context for autowiring can be created here,
and also there is a special contract for `@Beans` of type
`ApplicationContextInitializer`.

The bootstrap process ends by injecting initializers into the main
`SpringApplication` instance (i.e. the normal Spring Boot startup
sequence, whether it is running as a standalone app or deployed in an
application server). First a bootstrap context is created from the
classes found in `spring.factories` and then all `@Beans` of type
`ApplicationContextInitializer` are added to the main
`SpringApplication` before it is started.

[[customizing-bootstrap-property-sources]]
=== Customizing the Bootstrap Property Sources

The default property source for external configuration added by the
bootstrap process is the Config Server, but you can add additional
sources by adding beans of type `PropertySourceLocator` to the
bootstrap context (via `spring.factories`). You could use this to
insert additional properties from a different server, or from a
database, for instance.

As an example, consider the following trivial custom locator:

[source,java]
----
@Configuration
public class CustomPropertySourceLocator implements PropertySourceLocator {

    @Override
    public PropertySource<?> locate() {
        return new MapPropertySource("customProperty",
                Collections.<String, Object>singletonMap("property.from.sample.custom.source", "worked as intended"));
    }
}
----

If you create a jar with this class in it and then add a
`META-INF/spring.factories` containing:

----
org.springframework.cloud.bootstrap.BootstrapConfiguration=sample.custom.CustomPropertySourceLocator
----

then the "customProperty" `PropertySource` will show up in any
application that includes that jar on its classpath.

=== Security

If you use HTTP Basic security on the server then clients just need to
know the password (and username if it isn't the default). You can do
that via the config server URI, or via separate username and password
properties, e.g.

.bootstrap.yml
----
spring:
  cloud:
    config:
     uri: https://user:secret@myconfig.mycompany.com
----

or

.bootstrap.yml
----
spring:
  cloud:
    config:
     uri: https://myconfig.mycompany.com
     username: user
     password: secret
----

The `spring.cloud.config.password` and `spring.cloud.config.username`
values override anything that is provided in the URI.

If you deploy your apps on Cloud Foundry then the best way to provide
the password is through service credentials, e.g. in the URI, since
then it doesn't even need to be in a config file. An example which
works locally and for a user-provided service on Cloud Foundry named
"configserver":

.bootstrap.yml
----
spring:
  cloud:
    config:
     uri: ${vcap.services.configserver.credentials.uri:http://user:password@localhost:8888}

----

If you use another form of security you might need to provide a
`RestTemplate` to the `ConfigServicePropertySourceLocator` (e.g. by
grabbing it in the bootstrap context and injecting one).

