[[health-indicator]]
= Health Indicator

Config Server comes with a Health Indicator that checks whether the configured `EnvironmentRepository` is working.
By default, it asks the `EnvironmentRepository` for an application named `app`, the `default` profile, and the default label provided by the `EnvironmentRepository` implementation.

You can configure the Health Indicator to check more applications along with custom profiles and custom labels, as shown in the following example:

[source,yaml]
----
spring:
  cloud:
    config:
      server:
        health:
          repositories:
            myservice:
              label: mylabel
            myservice-dev:
              name: myservice
              profiles: development
----

You can disable the Health Indicator by setting `spring.cloud.config.server.health.enabled=false`.

Also, you can provide a custom `down` status of your own by setting property `spring.cloud.config.server.health.down-health-status` (valued to `"DOWN'` by default).

NOTE: If `spring.cloud.config.server.accept-empty` is `false` and the health indicator check
does not return any repository data the health indicator will return `down` status.
You can override this by setting `spring.cloud.config.server.health.accept-empty=true`.
